Nolmung/Nolmung-server

- src/main/java/ureca/nolmung/exception/BaseException.java
- src/main/java/ureca/nolmung/exception/ExceptionResponse.java
- src/main/java/ureca/nolmung/exception/ExceptionStatus.java
- src/main/java/ureca/nolmung/exception/ExceptionType.java
- src/main/java/ureca/nolmung/exception/Status.java
- src/main/java/ureca/nolmung/implementation/dummy/DummyException.java
- src/main/java/ureca/nolmung/implementation/dummy/DummyExceptionType.java
- src/main/java/ureca/nolmung/implementation/dummy/dummy.txt
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-109
> ## 💻 작업 내용
- 공통 예외처리 포맷 개발
---
> ## 🙇 특이 사항
- 마찬가지로 Implementation에 DummyException 관련 파일을 추가하여 어떤식으로 작성하는지 추가하였습니다.
- txt 파일로 어떤식으로 사용하는지 추가하였으니 참고하시면 될 것 같습니다.
---
-
---
> feat/SV-109: 공통 예외처리 포맷 개발

- src/main/java/ureca/nolmung/config/response/ResponseDto.java
- src/main/java/ureca/nolmung/config/response/ResponseStatus.java
- src/main/java/ureca/nolmung/config/response/ResponseUtil.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-106
> ## 💻 작업 내용
- 공통 응답 포맷 개발
---
> ## 🙇 특이 사항
---
- 코드 한 번씩 확인하고, 사용법 익히시면 됩니다~
---
> feat/SV-106: 공통 응답 포맷 개발

- .gitignore
- build.gradle
- src/main/resources/application.properties
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-77
> ## 💻 작업 내용
- application.properties -> application.yml 로 변경
- .gitignore 추가
- dependencies 추가
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-77: .gitignore, dependencies 추가 및 application 설정 파일 변경

- src/main/java/ureca/nolmung/jpa/badge/Badge.java
- src/main/java/ureca/nolmung/jpa/badgeCode/BadgeCode.java
- src/main/java/ureca/nolmung/jpa/bookmark/Bookmark.java
- src/main/java/ureca/nolmung/jpa/diary/Diary.java
- src/main/java/ureca/nolmung/jpa/diaryPlace/DiaryPlace.java
- src/main/java/ureca/nolmung/jpa/dog/Dog.java
- src/main/java/ureca/nolmung/jpa/dog/Enum/Gender.java
- src/main/java/ureca/nolmung/jpa/dogDiary/DogDiary.java
- src/main/java/ureca/nolmung/jpa/label/Label.java
- src/main/java/ureca/nolmung/jpa/media/Enum/MediaType.java
- src/main/java/ureca/nolmung/jpa/media/Media.java
- src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/jpa/recommend/Recommend.java
- src/main/java/ureca/nolmung/jpa/review/Review.java
- src/main/java/ureca/nolmung/jpa/reviewLabel/ReviewLabel.java
- src/main/java/ureca/nolmung/jpa/user/Enum/Gender.java
- src/main/java/ureca/nolmung/jpa/user/Enum/Provider.java
- src/main/java/ureca/nolmung/jpa/user/Enum/UserRole.java
- src/main/java/ureca/nolmung/jpa/user/Enum/UserStatus.java
- src/main/java/ureca/nolmung/jpa/user/User.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-194
> ## 💻 작업 내용
- 엔티티 설계
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-194: Add all entities

- src/main/java/ureca/nolmung/jpa/recommend/Recommend.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
- Recommend 테이블 데이터 타입 변경
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-194: Change data type in Recommend table

- build.gradle
- src/main/java/ureca/nolmung/config/swagger/SwaggerConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-184
> ## 💻 작업 내용
- SwaggerConfig 파일 작성
---
> ## 🙇 특이 사항
- Ureca 프론트엔드 노이진님이 만드신 Swaggy-Swagger을 사용해봤습니다!
---
- 사용방법은 제가 나중에 Controller를 만들때, 한 거 보고 사용하시면 될 것 같아요.
---
> feat/SV-184: Swagger 라이브러리 적용

- src/main/java/ureca/nolmung/business/review/ReviewService.java
- src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
- src/main/java/ureca/nolmung/business/review/dto/request/AddReviewReq.java
- src/main/java/ureca/nolmung/business/review/dto/response/AddReviewResp.java
- src/main/java/ureca/nolmung/exception/label/LabelException.java
- src/main/java/ureca/nolmung/exception/label/LabelExceptionType.java
- src/main/java/ureca/nolmung/exception/place/PlaceException.java
- src/main/java/ureca/nolmung/exception/place/PlaceExceptionType.java
- src/main/java/ureca/nolmung/exception/review/ReviewException.java
- src/main/java/ureca/nolmung/exception/review/ReviewExceptionType.java
- src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
- src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
- src/main/java/ureca/nolmung/jpa/dog/Dog.java
- src/main/java/ureca/nolmung/jpa/dog/Enum/DogSize.java
- src/main/java/ureca/nolmung/jpa/label/Label.java
- src/main/java/ureca/nolmung/jpa/label/LabelId.java
- src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/jpa/review/Review.java
- src/main/java/ureca/nolmung/jpa/reviewLabel/ReviewLabel.java
- src/main/java/ureca/nolmung/persistence/label/LabelRepository.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
- src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
- src/main/java/ureca/nolmung/persistence/user/UserRepository.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-31
- https://ureca7.atlassian.net/browse/SV-37
> ## 💻 작업 내용
- 후기 등록 시, 별점 및 라벨 저장
- 장소별 라벨 카운트 처리
- 후기 삭제 시 관련 데이터 삭제 
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-31: 후기 등록 및 삭제 API 개발

- build.gradle
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/business/place/response/PlaceDetailResponse.java
- src/main/java/ureca/nolmung/business/place/response/SearchedPlaceResponse.java
- src/main/java/ureca/nolmung/config/response/ResponseUtil.java
- src/main/java/ureca/nolmung/implementation/label/LabelManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceException.java
- src/main/java/ureca/nolmung/implementation/place/PlaceExceptionType.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/implementation/place/dtomapper/PlaceDtoMapper.java
- src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
- src/main/java/ureca/nolmung/jpa/badge/Badge.java
- src/main/java/ureca/nolmung/jpa/badgecode/BadgeCode.java
- src/main/java/ureca/nolmung/jpa/diaryplace/DiaryPlace.java
- src/main/java/ureca/nolmung/jpa/dogdiary/DogDiary.java
- src/main/java/ureca/nolmung/jpa/label/Label.java
- src/main/java/ureca/nolmung/jpa/label/LabelId.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/jpa/placeposition/PlacePosition.java
- src/main/java/ureca/nolmung/jpa/review/Review.java
- src/main/java/ureca/nolmung/jpa/reviewlabel/ReviewLabel.java
- src/main/java/ureca/nolmung/persistence/label/LabelRepository.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
- src/main/java/ureca/nolmung/persistence/placeposition/PlacePositionRepository.java
- src/main/java/ureca/nolmung/persistence/reviewlabel/ReviewLabelRepository.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
- src/main/resources/application.yml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-168
> ## 💻 작업 내용
- 장소 검색 API 개발
- 공간 데이터 타입 생성
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-168: 장소 검색 API 생성

- .gitignore
- application.yml 추가
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> env:gitignore 파일 수정

- Dockerfile
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-79
> ## 💻 작업 내용
- CI/CD 를 위한 Dockerfile 생성
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-79: Add Dockerfile

- build.gradle
- src/main/java/ureca/nolmung/business/oauth/OAuth2SucessHandler.java
- src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
- src/main/java/ureca/nolmung/business/oauth/dto/CustomOauth2User.java
- src/main/java/ureca/nolmung/business/user/UserService.java
- src/main/java/ureca/nolmung/business/user/dto/request/SignUpReq.java
- src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/java/ureca/nolmung/exception/jwt/JwtException.java
- src/main/java/ureca/nolmung/exception/jwt/JwtExceptionType.java
- src/main/java/ureca/nolmung/exception/user/UserException.java
- src/main/java/ureca/nolmung/exception/user/UserExceptionType.java
- src/main/java/ureca/nolmung/jpa/user/Enum/UserRole.java
- src/main/java/ureca/nolmung/jpa/user/User.java
- src/main/java/ureca/nolmung/persistence/user/UserRepository.java
- src/main/java/ureca/nolmung/presentation/controller/oauth/MyController.java
- src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-19
- https://ureca7.atlassian.net/browse/SV-159
- https://ureca7.atlassian.net/browse/SV-61
> ## 💻 작업 내용
- 소셜로그인 API 구현
- 회원가입 API 구현
- JWT 토큰 인증 로직 개발
---
> ## 🙇 특이 사항
- 추후 코드 리팩토링 예정
---
-
---
> feat/SV-19: 소셜로그인, 회원가입 API 구현 및 JWT 토큰 인증 로직 개발

- build.gradle
- src/main/java/ureca/nolmung/business/diary/response/PlaceDiaryResponse.java
- src/main/java/ureca/nolmung/business/labels/response/LabelResponse.java
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/business/place/request/PlaceOnMapServiceRequest.java
- src/main/java/ureca/nolmung/business/place/response/PlaceDetailResponse.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryException.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/label/LabelManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/jpa/label/Label.java
- src/main/java/ureca/nolmung/jpa/label/LabelId.java
- src/main/java/ureca/nolmung/jpa/placeposition/PlacePosition.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
- src/main/java/ureca/nolmung/persistence/diaryplace/DiaryPlaceRepository.java
- src/main/java/ureca/nolmung/persistence/media/MediaRepository.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/persistence/placeposition/PlacePositionRepository.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
- src/main/java/ureca/nolmung/presentation/controller/place/request/PlaceOnMapRequest.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-198
> ## 💻 작업 내용
- 지도에서 장소 검색 API 개발
---
> ## 🙇 특이 사항
- 리팩토링 필요합니다.
---
-
---
> Feat/sv-198: 지도에서 장소 검색 API 개발

- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/persistence/diaryplace/DiaryPlaceRepository.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
- 오탈자 수정 (수정한 파일 : DiaryPlaceRepository.java, DiaryManager.java)
---
> ## 🙇 특이 사항
-
---
-
---
> hotfix :오탈자 수정

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
- src/main/java/ureca/nolmung/business/diary/dto/request/AddDiaryReq.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/dog/DogException.java
- src/main/java/ureca/nolmung/implementation/dog/DogExceptionType.java
- src/main/java/ureca/nolmung/implementation/media/MediaException.java
- src/main/java/ureca/nolmung/implementation/media/MediaExceptionType.java
- src/main/java/ureca/nolmung/jpa/diary/Diary.java
- src/main/java/ureca/nolmung/jpa/media/Media.java
- src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
- src/main/java/ureca/nolmung/persistence/dogdiary/DogDiaryRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-163
> ## 💻 작업 내용
- 오늘멍 등록 api 구현
---
> ## 🙇 특이 사항
- 이미지 url 저장 제외, S3 구축 후 구현 예정
---
-
---
> feat/SV-163: 오늘멍 등록 API 구현

- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-200
> ## 💻 작업 내용
- 시큐리티 설정에 swagger 관련 설정 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-200: 시큐리티 설정에 swagger 관련 설정 추가

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/business/dog/dto/request/AddDogReq.java
- src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
- src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
- src/main/java/ureca/nolmung/implementation/user/UserManager.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-33
> ## 💻 작업 내용
- 반려견 프로필 등록 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-33: 반려견 프로필 등록 API 구현

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
- src/main/java/ureca/nolmung/business/diary/dto/response/AddDiaryResp.java
- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
- src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
- src/main/java/ureca/nolmung/implementation/user/UserManager.java
- src/main/java/ureca/nolmung/jpa/diary/Diary.java
- src/main/java/ureca/nolmung/jpa/user/User.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
- src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
- src/main/java/ureca/nolmung/persistence/dogdiary/DogDiaryRepository.java
- src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-147
> ## 💻 작업 내용
- 오늘멍 전체조회 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-147: 오늘멍 전체조회 API 구현

- build.gradle
- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
- src/main/java/ureca/nolmung/business/recommend/dto/response/RecommendResp.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsConfig.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-117
> ## 💻 작업 내용
- 수도권 전체 개인 맞춤형 추천 로직 구현
---
> ## 🙇 특이 사항
- x
---
- 
---
> feat/SV-117: 수도권 전체 개인 맞춤형 추천 로직 구현

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/jpa/dog/Dog.java
- src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-46
> ## 💻 작업 내용
- 반려견 프로필 수정 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-46: 반려견 프로필 수정 API 구현

- build.gradle
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/business/place/response/PlaceDetailResponse.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/persistence/diaryplace/DiaryPlaceRepository.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-36
> ## 💻 작업 내용
- 장소 상세 조회 API 개발
---
> ## 🙇 특이 사항
- 필터링 기능이 어느정도 구현되어 있기는 합니다. 즐겨찾기 기능 개발하면 필터에 추가해서 필터링 기능 완성할게요
---
-
---
> feat/SV-36: 장소 상세 정보 조회 API 개발

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-47
> ## 💻 작업 내용
- 반려견 프로필 삭제 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-47: 반려견 프로필 삭제 API 구현

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-172
> ## 💻 작업 내용
- 반려견 프로필 조회 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-172: 반려견 프로필 조회 API 구현

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/business/dog/DogUseCase.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/persistence/dog/DogRepository.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-108 
> ## 💻 작업 내용
- 반려견 프로필 목록 조회 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-108: 반려견 프로필 목록 조회 API 구현

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
- src/main/java/ureca/nolmung/business/recommend/dto/response/RecommendResp.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-111
> ## 💻 작업 내용
- 수도권 전체 즐겨찾기 수 기준 장소 추천 로직 구현
-  반려견 정보 기준 장소 추천 로직 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-111: 수도권 전체 즐겨찾기 수, 반려견 정보 기준 장소 추천 로직 구현

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
- src/main/java/ureca/nolmung/jpa/user/User.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-21
> ## 💻 작업 내용
- 거주지 근처 장소 추천 로직 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/sv-21: 거주지 근처 장소 추천 로직 구현

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/business/bookmark/BookmarkUseCase.java
- src/main/java/ureca/nolmung/exception/ApiControllerAdvice.java
- src/main/java/ureca/nolmung/exception/ExceptionResponse.java
- src/main/java/ureca/nolmung/exception/bookmark/BookmarkExceptionType.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/presentation/controller/bookmark/BookmarkController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-100
> ## 💻 작업 내용
- 즐겨찾기 삭제 API 개발
---
> ## 🙇 특이 사항
- 일단 DeleteMapping을 사용해서 물리적으로 삭제 처리 했습니다. 후에 시간이 된다면 논리 삭제로 바꿔도 될 것 같습니다.
---
-
---
> feat/SV-100: 즐겨찾기 삭제 API 개발

- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/jpa/place/Enum/Category.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-197
> ## 💻 작업 내용
- 장소 검색 필터링 기능 개발
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-197: 장소 검색 필터링 기능 개발

- src/main/java/ureca/nolmung/config/swagger/SwaggerConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-203
> ## 💻 작업 내용
- 스웨거 CORS에러 수정
---
> ## 🙇 특이 사항
-
---
-
---
> refactor/SV-203: 스웨거 CORS에러 해결

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
- src/main/java/ureca/nolmung/implementation/diaryplace/DiaryPlaceManager.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/implementation/dogdiary/DogDiaryManager.java
- src/main/java/ureca/nolmung/implementation/media/MediaManager.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
- src/main/java/ureca/nolmung/persistence/diaryplace/DiaryPlaceRepository.java
- src/main/java/ureca/nolmung/persistence/dogdiary/DogDiaryRepository.java
- src/main/java/ureca/nolmung/persistence/media/MediaRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-157
> ## 💻 작업 내용
- 오늘멍 상세조회 API 구현
- 상세 데이터 : 일기 기본 정보 / 함께한 반려견 정보 / 방문 장소 정보 / 일기에 포함된 미디어 정보
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-157: 오늘멍 상세조회 API 구현

- build.gradle
- src/main/java/ureca/nolmung/config/swagger/SwaggerConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-203
> ## 💻 작업 내용
- 스웨거 지도에서 장소 검색 API 오류 수정
- Swaggy-Swagger 라이브러리 제거
---
> ## 🙇 특이 사항
-
---
-
---
> refactor/SV-203: 스웨거 지도에서 장소 검색 API 오류 해결

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
- src/main/java/ureca/nolmung/business/diary/dto/response/DeleteDiaryResp.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/jpa/diary/Diary.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-150
> ## 💻 작업 내용
- 오늘멍 삭제 API 구현
- 삭제 시 관련 데이터 CASCADE 적용하여 함께 삭제
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-150: 오늘멍 삭제 API 구현

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/business/diary/DiaryUseCase.java
- src/main/java/ureca/nolmung/business/diary/dto/request/AddDiaryReq.java
- src/main/java/ureca/nolmung/business/diary/dto/request/UpdateDiaryReq.java
- src/main/java/ureca/nolmung/business/diary/dto/response/UpdateDiaryResp.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/jpa/diary/Diary.java
- src/main/java/ureca/nolmung/persistence/media/MediaRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-149
> ## 💻 작업 내용
- 오늘멍 수정 API 구현
- 제목, 내용, 미디어(이미지, 동영상), 함께한 반려견 수정
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-149: 오늘멍 수정 API 구현

- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-209
> ## 💻 작업 내용
- 후기 시스템, 다이어리 시스템 Controller에 Swagger 어노테이션 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-209: Swagger 관련 어노테이션 추가

- src/main/java/ureca/nolmung/business/badge/BadgeService.java
- src/main/java/ureca/nolmung/business/badge/BadgeUseCase.java
- src/main/java/ureca/nolmung/business/badge/dto/request/BadgeReq.java
- src/main/java/ureca/nolmung/business/badge/dto/response/BadgeResp.java
- src/main/java/ureca/nolmung/implementation/badge/BadgeManager.java
- src/main/java/ureca/nolmung/implementation/badge/dtomapper/BadgeDtoMapper.java
- src/main/java/ureca/nolmung/persistence/badge/BadgeRepository.java
- src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-145
> ## 💻 작업 내용
- 배지 조회 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-145: 배지 조회 API 구현

- src/main/java/ureca/nolmung/business/dog/DogService.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-46
- https://ureca7.atlassian.net/browse/SV-47
- https://ureca7.atlassian.net/browse/SV-172
- https://ureca7.atlassian.net/browse/SV-108
> ## 💻 작업 내용
- @AuthenticationPrincipal을 사용하여 로그인한 사용자 정보 조회 로직 수정 (반려견 프로필 수정 API, 반려견 프로필 삭제 API, 반려견 프로필 조회 API, 반려견 프로필 목록 조회 API)
- 불필요한 코드 삭제
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-46: @AuthenticationPrincipal을 사용하여 로그인한 사용자 정보 조회 로직 수정

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/business/bookmark/BookmarkUseCase.java
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/jpa/banword/trie/Trie.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/presentation/controller/bookmark/BookmarkController.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-96
> ## 💻 작업 내용
- 즐겨찾기 AuthenticationPrincipal 적용
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-96: 즐겨찾기 AuthenticationPrincipal 적용

- src/main/java/ureca/nolmung/business/review/ReviewService.java
- src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
- src/main/java/ureca/nolmung/business/review/dto/response/ReviewLabelResp.java
- src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
- src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
- src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
- src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
- src/main/java/ureca/nolmung/presentation/controller/diary/DiaryController.java
- src/main/java/ureca/nolmung/presentation/controller/dog/DogController.java
- src/main/java/ureca/nolmung/presentation/controller/dummy/DummyController.java
- src/main/java/ureca/nolmung/presentation/controller/oauth/UserController.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-211
> ## 💻 작업 내용
- 내가 쓴 리뷰 조회 API 구현
- 공통 수정 사항 반영 : @RequestMapping에 "/api" 제거
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-211: 내가 쓴 리뷰 조회 API 구현 및 공통 수정 사항 반영

- .github/workflows/gradle.yml
- build.gradle
- docker-compose.yml
- prometheus.yml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-86
> ## 💻 작업 내용
- 서버 모니터링 환경 구축
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-86: 서버 모니터링 환경 구축

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/implementation/badge/BadgeManager.java
- src/main/java/ureca/nolmung/implementation/badgecode/BadgeCodeException.java
- src/main/java/ureca/nolmung/implementation/badgecode/BadgeCodeExceptionType.java
- src/main/java/ureca/nolmung/jpa/badge/Badge.java
- src/main/java/ureca/nolmung/jpa/user/User.java
- src/main/java/ureca/nolmung/persistence/badge/BadgeRepository.java
- src/main/java/ureca/nolmung/persistence/badgecode/BadgeCodeRepository.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-212
> ## 💻 작업 내용
- 오늘멍 작성 시, 배지 추가 로직 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-212: 오늘멍 작성 시, 배지 추가 로직 구현

- .github/workflows/gradle-dev.yml
- .github/workflows/gradle-prod.yml
- Dockerfile.dev
- Dockerfile.prod
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-88
> ## 💻 작업 내용
- 워크플로 분리
- Dockerfile 분리
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-88: 개발/운영 서버 환경 분리 작업

- src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
- src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-144
> ## 💻 작업 내용
- UserResp에 사용자 프로필, 이메일 정보 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-144: UserResp에 사용자 프로필, 이메일 정보 추가

- .gitignore
- src/main/java/ureca/nolmung/config/swagger/SwaggerConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-203
> ## 💻 작업 내용
- 개발 서버 Swagger 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-203: 개발 서버 스웨거 추가

- Dockerfile.dev
- Dockerfile.prod
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-203
> ## 💻 작업 내용
- Swagger 개발 서버 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-203: 스웨거 개발 서버 추가

- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
- src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-219
> ## 💻 작업 내용
- 응답값에 강아지 이름 추가
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-219: 오늘멍 상세조회 응답값 추가

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-218
> ## 💻 작업 내용
- 추천 시스템 코드 리팩토링
---
> ## 🙇 특이 사항
-
---
-
---
> refact/sv-218: 추천 시스템 코드 리팩토링

- .github/workflows/gradle-dev.yml
- docker-compose-dev.yml
- docker-compose.yml
- promtail-config.yml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-220
> ## 💻 작업 내용
- 개발 서버 도커를 사용하여 redis 구축
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-220: 개발 서버 redis 구축

- .github/workflows/gradle-dev.yml
- build.gradle
- docker-compose-dev.yml
- docker-compose.yml
- promtail-config.yml
- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/business/recommend/RecommendUseCase.java
- src/main/java/ureca/nolmung/config/aws/AwsConfig.java
- src/main/java/ureca/nolmung/config/redis/RedisConfig.java
- src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
- src/main/java/ureca/nolmung/implementation/recommend/dtomapper/RecommendDtoMapper.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.04 추천시스템 추가

- src/main/java/ureca/nolmung/presentation/controller/recommend/RecommendController.java
> ## 📝 관련 이슈
---
- 
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.04 추천시스템 추가 수정

- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
> ## 📝 관련 이슈
---
- 
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.04 추천 시스템 매니저 수정

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-19
> ## 💻 작업 내용
- 시큐리티 파일 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-19: 시큐리티 파일 수정

- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-211
> ## 💻 작업 내용
- GetMapping 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-211: GetMapping 수정

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
- GetMapping 수정
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.04 GetMapping 수정

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> fix: gradle-dev.yml

- .github/workflows/gradle-dev.yml
- .github/workflows/gradle-prod.yml
- docker-compose-dev.yml
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.04 워크플로 수정

- src/main/java/ureca/nolmung/business/review/ReviewService.java
- src/main/java/ureca/nolmung/business/review/dto/response/LabelResp.java
- src/main/java/ureca/nolmung/business/review/dto/response/ReviewLabelResp.java
- src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
- src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-211
> ## 💻 작업 내용
- 내가 쓴 리뷰 조회 API 에 장소 ID 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-211: 내가 쓴 리뷰 조회 API 에 장소 ID 추가

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/jpa/user/User.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-227
> ## 💻 작업 내용
- 거주지 기반 추천 로직 변경 ( 거주지 위도 경도를 가지고 근처 장소 추천
---
> ## 🙇 특이 사항
- 우선은 5키로 이내의 장소 추천으로 정했는데 추후에 변경 가능합니다.
---
-
---
> refact/sv-227: 추천 시스템 추가 리팩토링

- src/main/java/ureca/nolmung/business/user/dto/request/UserReq.java
- src/main/java/ureca/nolmung/business/user/dto/response/UserResp.java
- src/main/java/ureca/nolmung/implementation/user/dtomapper/UserDtoMapper.java
- src/main/java/ureca/nolmung/jpa/user/User.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-154
- https://ureca7.atlassian.net/browse/SV-144
- https://ureca7.atlassian.net/browse/SV-159
> ## 💻 작업 내용
- 사용자 정보 나이에서 생년월일로 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-154 : 사용자 정보 나이에서 생년월일로 수정

- src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
- src/main/java/ureca/nolmung/exception/ApiControllerAdvice.java
- src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-224
> ## 💻 작업 내용
- 후기 api url 수정 및 예외처리 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-224: api url 수정 및 예외처리 추가

- .github/workflows/gradle-dev.yml
- .github/workflows/gradle-prod.yml
- docker-compose.yml
- local-config.yml
- promtail-config.yml
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/business/place/PlaceUseCase.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryCustom.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-222
> ## 💻 작업 내용
- 장소 조회 필터링 API 수정
- 강아지 크기, 별점 필터 제거 및 방문 여부 필터 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat(SV-222): 장소 조회 필터링 API 수정

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-226
> ## 💻 작업 내용
- 다이어리 시스템 조회 시 트랜잭션 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-226: 다이어리 시스템 리팩토링

- src/main/java/ureca/nolmung/jpa/place/Place.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-234
> ## 💻 작업 내용
- 장소 평균 별점 소수점 첫째자리까지 처리
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-234: 장소 평균 별점 소수점 첫째자리까지 처리

- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
> ## 📝 관련 이슈
---
> ## 💻 작업 내용
- JWT 토큰 확인 안해도 되는 경로 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-225 : JWT 토큰 확인 안해도 되는 경로 수정

- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-222
> ## 💻 작업 내용
- 장소 상세 정보 조회 API 수정
---
> ## 🙇 특이 사항
-
---
-
---
> feat(SV-222): 장소 상세 조회 API 수정

- src/main/java/ureca/nolmung/business/dog/dto/request/DogReq.java
- src/main/java/ureca/nolmung/business/dog/dto/response/DogResp.java
- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/implementation/dog/dtomapper/DogDtoMapper.java
- src/main/java/ureca/nolmung/jpa/dog/Dog.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-33
- https://ureca7.atlassian.net/browse/SV-46
- https://ureca7.atlassian.net/browse/SV-47
- https://ureca7.atlassian.net/browse/SV-172
- https://ureca7.atlassian.net/browse/SV-108
> ## 💻 작업 내용
- DogReq, DogResp 수정
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-33 : DogReq, DogResp 수정

- build.gradle
- src/main/resources/logback-variables.properties
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-90
> ## 💻 작업 내용
- build.gradle에 로그 파일이 저장될 서버 경로 지정
---
> ## 🙇 특이 사항
-
---
-
---
> refact(SV-90): 로깅 시스템 구축

- build.gradle
- src/main/resources/logback-spring.xml
- src/main/resources/logback-variables.properties
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-90
> ## 💻 작업 내용
- logback-spring.xml 수정
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.06 logback-spring.xml 수정

- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-61
> ## 💻 작업 내용
- JWT 필터 제외할 경로 추가
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-61 : JWT 필터 제외할 경로 추가

- docker-compose.yml
- src/main/resources/logback-spring.xml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-90
> ## 💻 작업 내용
- logback-spring.xml 작성
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-90: logback-spring.xml 작성

- .gitignore
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/resources/logback-spring.xml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-236
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> refact(SV-236): SecurityConfig Origin 추가

- src/main/resources/logback-spring.xml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-236
> ## 💻 작업 내용
- log파일 로그 색 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-90: log파일 로그 색 추가

- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-222
> ## 💻 작업 내용
- 일기 조회 시, media 널인 우 처리
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-222: 일기 조회 시, media 널 처리

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-222
> ## 💻 작업 내용
- 북마크 삭제 API 수정
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-222: 북마크 삭제 API 수정

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-247
> ## 💻 작업 내용
-SecurityConfig 장소 경로 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-247: SecurityConfig 장소 경로 추가

- docker-compose-monitor.yml
- docker-compose-prod.yml
- prometheus.yml
- promtail-config.yml
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-240
> ## 💻 작업 내용
- 모니터링 서버를 위한 docker-compose-monitor.yml 생성
- 기존 EC2 서버에 있는 prometheus, grafana, loki를 분리
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-240: 모니터링 서버를 위한 yml파일 추가 및 수정

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceExceptionType.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-257
> ## 💻 작업 내용
- 북마크 삭제 시 장소 테이블 북마크 개수 감소
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-257: 북마크 삭제 시 장소 테이블 북마크 개수 감소

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/business/place/PlaceService.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/presentation/controller/place/PlaceController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-258
> ## 💻 작업 내용
- BookmarkService, BookmarkManager 추상화 레벨 맞추기
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-258: 북마크 코드 리팩토링

- src/main/java/ureca/nolmung/business/oauth/OAuthUserServiceImplement.java
- src/main/java/ureca/nolmung/business/oauth/dto/response/OauthLoginRes.java
- src/main/java/ureca/nolmung/config/jwt/JWTUtil.java
- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
- src/main/java/ureca/nolmung/presentation/controller/user/OauthController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-61
> ## 💻 작업 내용
- 액세스토큰을 ResponseBody로 받을 수 있도록 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-61 : 액세스토큰을 ResponseBody로 받을 수 있도록 수정

- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-260
> ## 💻 작업 내용
- 장소 상세 조회 일기 조회 실패 문제 해결
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-260: 장소 상세 조회 일기 조회 실패 문제 해결

- src/main/java/ureca/nolmung/presentation/controller/user/OauthController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-261
> ## 💻 작업 내용
- 하드코딩된 프론트엔드 URL을 동적 URL로 변경
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-261 : 하드코딩된 프론트엔드 URL을 동적 URL로 변경

- src/main/java/ureca/nolmung/business/bookmark/BookmarkService.java
- src/main/java/ureca/nolmung/business/bookmark/BookmarkUseCase.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/implementation/place/PlaceManager.java
- src/main/java/ureca/nolmung/persistence/bookmark/BookmarkRepository.java
- src/main/java/ureca/nolmung/presentation/controller/bookmark/BookmarkController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-262
> ## 💻 작업 내용
- 기존 북마크 id로 삭제하던 요청을 장소 id로 변경했습니다.
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-262: 북마크 삭제 시, 장소 아이디로 삭제 요청

- src/main/java/ureca/nolmung/business/place/response/SearchedPlaceResponse.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-263
> ## 💻 작업 내용
- 장소 검색 시, acceptSize 응답 데이터 추가
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-263: 장소 검색 시, acceptSize 응답 데이터 추가

- src/main/java/ureca/nolmung/business/bookmark/response/BookmarkResponse.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-265
> ## 💻 작업 내용
- 즐겨찾기 목록 조회 시, 장소 id 제공
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-265: 즐겨찾기 목록 조회 시, 장소 id 제공

- src/main/java/ureca/nolmung/config/jwt/HttpRequestEndpointChecker.java
- src/main/java/ureca/nolmung/config/jwt/JwtAccessDeniedHandler.java
- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/ureca/nolmung/config/jwt/JwtAuthenticationFilter.java
- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-264
> ## 💻 작업 내용
- 404 에러 예외처리 코드 추가
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-264 : 404 에러 예외처리 코드 추가

- src/main/java/ureca/nolmung/business/user/dto/response/SignUpResp.java
- src/main/java/ureca/nolmung/presentation/controller/user/UserController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-266
> ## 💻 작업 내용
- 회원가입 API 결과값에 액세스토큰 포함되도록 수정
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-266 : 회원가입 API 결과값에 액세스토큰 포함되도록 수정

- src/main/java/ureca/nolmung/implementation/dog/DogManager.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepositoryImpl.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-267
> ## 💻 작업 내용
- 장소 조회 시, Place와 PlacePosition 간의 N+1 문제 해결
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-267: 장소 조회 시, N+1 문제 해결

- src/main/java/ureca/nolmung/business/diary/DiaryService.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryExceptionType.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/persistence/diary/DiaryRepository.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-275
> ## 💻 작업 내용
- 오늘멍 하루에 하나만 작성가능하도록 예외처리
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-275: 오늘멍 하루에 하나만 작성가능하도록 예외처리

- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
- src/main/java/ureca/nolmung/implementation/diary/DiaryManager.java
- src/main/java/ureca/nolmung/jpa/place/Place.java
- src/main/java/ureca/nolmung/presentation/controller/HealthCheckController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-315
> ## 💻 작업 내용
- 에러 로그 테스트를 위한 API 개발
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-315: 에러 로그 테스트를 위한 API 개발

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-316
> ## 💻 작업 내용
- SecurityConfig Origin 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-316: SecurityConfig Origin 추가

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/persistence/place/PlaceRepository.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-320
> ## 💻 작업 내용
- 추천 리스트를 5개 반환하는 것에서 10개를 반환하는 것으로 수정하였습니다.
- 가져올 개수를 매개변수로 받도록 수정하였습니다.
---
> ## 🙇 특이 사항
-
---
-
---
> refact/sv-320: 추천 리스트 10개로 늘리기

- src/main/java/ureca/nolmung/presentation/controller/HealthCheckController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-316
> ## 💻 작업 내용
- SecurityConfig errors/log 경로 토큰 인증 제외
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-316: SecurityConfig errors/log 경로 토큰 인증 제외

- src/main/java/ureca/nolmung/business/review/ReviewService.java
- src/main/java/ureca/nolmung/business/review/ReviewUseCase.java
- src/main/java/ureca/nolmung/business/review/dto/response/ReviewResp.java
- src/main/java/ureca/nolmung/implementation/review/ReviewManager.java
- src/main/java/ureca/nolmung/implementation/review/dtomapper/ReviewDtoMapper.java
- src/main/java/ureca/nolmung/persistence/review/ReviewRepository.java
- src/main/java/ureca/nolmung/presentation/controller/review/ReviewController.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-323
> ## 💻 작업 내용
- 오늘 작성한 리뷰 조회 API 구현
---
> ## 🙇 특이 사항
-
---
-
---
> feat/SV-323 : 오늘 작성한 리뷰 조회 API 구현

- src/main/java/ureca/nolmung/config/security/SecurityConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-334
> ## 💻 작업 내용
- SecurityConfig CORS 설정 추가
- "https://nolmung-official.netlify.app/" 추가
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-334: SecurityConfig CORS 설정 추가

- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryDetailResp.java
- src/main/java/ureca/nolmung/business/diary/dto/response/DiaryListResp.java
- src/main/java/ureca/nolmung/implementation/diary/dtomapper/DiaryDtoMapper.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-370
> ## 💻 작업 내용
- 오늘멍 전체 조회 및 상세 조회시 createdAt값을 LocalDateTime 으로 반환
---
> ## 🙇 특이 사항
-
---
-
---
> fix/SV-370: 오늘멍 전체 조회 및 상세 조회시 createdAt값을 LocalDateTime 으로 반환

- Dockerfile.dev
- Dockerfile.prod
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-373
> ## 💻 작업 내용
- Dockerfile 타임존 추가
---
> ## 🙇 특이 사항
-
---
-
---
> env/SV-373: Dockerfile 타임존 추가

- src/main/java/ureca/nolmung/business/recommend/RecommendService.java
- src/main/java/ureca/nolmung/implementation/recommend/AwsPersonalizeManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RecommendManager.java
- src/main/java/ureca/nolmung/implementation/recommend/RedisManager.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-374
> ## 💻 작업 내용
- 주석 추가
---
> ## 🙇 특이 사항
-
---
-
---
> refact/SV-374: 주석 추가

- README.md
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-383
> ## 💻 작업 내용
- 산출물 링크 수정
---
> ## 🙇 특이 사항
-
---
-
---
> docs/SV-383: 산출물 링크 수정

- README.md
> ## 📝 관련 이슈
---
- 
> ## 💻 작업 내용
- 산출물 링크 각각 달기
---
> ## 🙇 특이 사항
-
---
-
---
> docs/SV-383 : 산출물 링크 수정

- README.md
> ## 📝 관련 이슈
---
- 리드미 업데이트
> ## 💻 작업 내용
-
---
> ## 🙇 특이 사항
-
---
-
---
> deploy: 24.12.19 v2.0

- build.gradle
- src/main/java/ureca/nolmung/config/aws/AwsConfig.java
- src/main/java/ureca/nolmung/implementation/bookmark/BookmarkManager.java
- src/main/java/ureca/nolmung/implementation/recommend/CsvGeneratorManager.java
- src/main/java/ureca/nolmung/implementation/recommend/S3Manager.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchConfig.java
- src/main/java/ureca/nolmung/implementation/recommend/batch/BatchScheduler.java
- src/main/java/ureca/nolmung/persistence/bookmark/BookmarkRepository.java
- src/test/java/ureca/nolmung/implementation/recommend/CsvGeneratorManagerTest.java
> ## 📝 관련 이슈
---
- https://ureca7.atlassian.net/browse/SV-348
> ## 💻 작업 내용
- personalize 모델 자동 학습 로직 구현
---
> ## 🙇 특이 사항
- 
---
-
---
> feat/sv-348: personalize 모델 자동 학습 로직 구현

- README.md
> ## 📝 관련 이슈
---
- 
> ## 💻 작업 내용
- docs/SV-383: 기획안 링크 수정
---
> ## 🙇 특이 사항
-
---
-
---
> docs/SV-383: 기획안 링크 수정
